
[tool.djlint]
use_gitignore = true
blank_line_after_tag = "extends"
blank_line_before_tag = "block"
ignore = "H030,H031,H021"
indent = 2
profile = "django"
format_css = true

[tool.djlint.css]
indent_size = 2
