
[tool.djlint]
use_gitignore = true
blank_line_after_tag = "extends"
blank_line_before_tag = "block"
ignore = "H006,H021,H030,H031"
indent = 2
profile = "django"
format_css = true

[tool.djlint.css]
indent_size = 2
