# Generated by Django 4.1.1 on 2022-09-27 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0002_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="AccountOwner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="toolkit.user"
            ),
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
