# Generated by Django 4.1.1 on 2022-10-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_alter_character_accountowner_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('Armor_Type', models.CharField(max_length=6)),
                ('Base_Value', models.FloatField()),
                ('Armor_Class_Change', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Stealth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GenericItem',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('Base_Value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Rarity', models.CharField(max_length=20)),
                ('Effect_Description', models.CharField(max_length=255)),
                ('Visual_Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Damage_Type', models.CharField(max_length=30)),
                ('Weapon_Type', models.CharField(max_length=14)),
                ('Damage_Die', models.CharField(max_length=10)),
                ('Base_Value', models.FloatField()),
                ('Max_Range', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Ammo', models.CharField(blank=True, max_length=7)),
                ('Special_Characteristics', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('Challenge_Rating', models.FloatField()),
                ('Strength', models.IntegerField()),
                ('Dexterity', models.IntegerField()),
                ('Constitution', models.IntegerField()),
                ('Intelligence', models.IntegerField()),
                ('Wisdom', models.IntegerField()),
                ('Charisma', models.IntegerField()),
                ('Gold_Modifier', models.FloatField(blank=True)),
                ('Creature_Tags', models.ManyToManyField(to='toolkit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loot_Type', models.CharField(max_length=20)),
                ('Total_Value', models.FloatField()),
                ('Money', models.FloatField()),
                ('Armors', models.ManyToManyField(blank=True, to='toolkit.armor')),
                ('Generic_Items', models.ManyToManyField(blank=True, to='toolkit.genericitem')),
                ('Magical_Items', models.ManyToManyField(blank=True, to='toolkit.magicitem')),
                ('Weapons', models.ManyToManyField(blank=True, to='toolkit.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encounter_Type', models.CharField(max_length=20)),
                ('Number_Of_Characters', models.IntegerField()),
                ('Average_Character_Levels', models.FloatField()),
                ('Encounter_Tags', models.ManyToManyField(blank=True, to='toolkit.tag')),
                ('Monsters', models.ManyToManyField(to='toolkit.monster')),
                ('Reward', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.generatedloot')),
            ],
        ),
    ]
