# Generated by Django 4.1.1 on 2022-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_armor_genericitem_magicitem_tag_weapon_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='Ammo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Special_Characteristics',
            field=models.IntegerField(),
        ),
    ]
