# Generated by Django 4.1.1 on 2022-10-14 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolkit', '0006_alter_weapon_ammo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='AccountOwner',
        ),
        migrations.AddField(
            model_name='character',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedencounter',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedloot',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Ammo',
            field=models.CharField(blank=True, default='None', max_length=7),
            preserve_default=False,
        ),
    ]
