# Generated by Django 4.1.1 on 2022-11-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0007_remove_character_accountowner_character_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='Gold_Modifier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
