# Generated by Django 4.1.1 on 2022-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0008_alter_monster_gold_modifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='magicitem',
            name='Effect_Description',
        ),
        migrations.RemoveField(
            model_name='magicitem',
            name='Visual_Description',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Charisma',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Constitution',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Dexterity',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Intelligence',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Strength',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='Wisdom',
        ),
        migrations.AddField(
            model_name='genericitem',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magicitem',
            name='Attuned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magicitem',
            name='Type',
            field=models.CharField(default='Trinket', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Alignment',
            field=models.CharField(default='Good', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Size',
            field=models.CharField(default='Medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Type',
            field=models.CharField(default='Human', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='Armor_Class_Change',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Special_Characteristics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
