# Generated by Django 4.1.1 on 2022-11-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0010_savecache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savecache",
            name="character",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="toolkit.character",
            ),
        ),
    ]
