# Generated by Django 4.1.1 on 2022-11-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0012_rename_savecache_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedencounter',
            name='Average_CR',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
    ]
