# Generated by Django 4.1.1 on 2022-11-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0013_cache_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='encounter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolkit.generatedencounter'),
        ),
    ]
