# Generated by Django 4.1.1 on 2022-11-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0013_generatedencounter_average_cr"),
        ("toolkit", "0014_cache_encounter"),
    ]

    operations = []
