# Generated by Django 4.1.1 on 2022-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0015_merge_20221116_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
                ('Stat', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='generatedencounter',
            name='Average_CR',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Creature_Tags',
            field=models.ManyToManyField(blank=True, to='toolkit.tag'),
        ),
        migrations.AddField(
            model_name='character',
            name='Character_Proficiencies',
            field=models.ManyToManyField(blank=True, null=True, to='toolkit.proficiencies'),
        ),
    ]
