# Generated by Django 4.1.1 on 2022-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0017_alter_character_character_proficiencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedencounter',
            name='Monsters',
            field=models.ManyToManyField(blank=True, to='toolkit.monster'),
        ),
    ]
