# Generated by Django 4.1.1 on 2022-11-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0017_alter_character_character_proficiencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('ShortName', models.CharField(max_length=20)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='Armor_Class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Hitpoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Initiative',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='Source',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proficiencies', models.ManyToManyField(to='toolkit.proficiencies')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='Class',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.clazz'),
        ),
        migrations.AlterField(
            model_name='character',
            name='Race',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.race'),
        ),
    ]
