# Generated by Django 4.1.1 on 2022-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0018_race_source_monster_armor_class_monster_hitpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='StatPrecedence',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='Class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.clazz'),
        ),
        migrations.AlterField(
            model_name='character',
            name='Race',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.race'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Armor_Class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Hitpoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Initiative',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
