# Generated by Django 4.1.1 on 2022-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0019_clazz_statprecedence_alter_character_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='Size',
            field=models.CharField(default='medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='Speed',
            field=models.IntegerField(default=30),
        ),
    ]
