# Generated by Django 4.1.1 on 2022-11-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0020_race_size_alter_race_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='Options',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='Options',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
