# Generated by Django 4.1.1 on 2022-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0022_clazz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='HitDice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
