# Generated by Django 4.1.1 on 2022-11-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0018_alter_generatedencounter_monsters"),
        ("toolkit", "0023_clazz_hitdice"),
    ]

    operations = []
