name: Django Lint CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: djlint
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: |
          pip install djlint
          pip install -r requirements.txt
      - name: djlint format
        run: |
          djlint ./ --reformat --quiet --warn
        # continue-on-error: true
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'John Schiltz'
          git config --global user.email '45466247+schiltz3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git status

          # git pull origin HEAD:${{ github.head_ref }}
          git commit -am "Automatic Template Formatting"
          # git remote set-head ${{ github.head_ref}}
          git push
      - name: djlint lint
        run: |
          djlint ./ --lint
