name: "Doc builder"
on:
  pull_request:
    branches: [ pages ]
  push:
    branches: [ pages ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Install Dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements/prod.txt
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "Sphinx/"

      - name: Move docs to published folder
        run: |
          rm -r docs
          mkdir -p docs
          cp -a Sphinx/_build/html/. docs/
          cp Sphinx/_config.yml docs/
          cp Sphinx/.nojekyll docs/

      - name: Push changes
        run: |
          git config --global user.name 'John Schiltz'
          git config --global user.email '45466247+schiltz3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "Docs built"
          git push